name: Bug Report
description: 报告一个可复现的问题
labels: [bug]
title: "[Bug]: "
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 提交前检查
      options:
        - label: 我已搜索现有 Issues，确认不是重复问题
          required: true
        - label: 我已阅读 CONTRIBUTING.md 并提供最小复现信息
          required: true

  - type: textarea
    id: summary
    attributes:
      label: 问题描述
      description: 请简要描述问题现象。
      placeholder: 在什么情况下发生了什么问题？
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 请提供可稳定复现的步骤。
      placeholder: |
        1. 进入页面 ...
        2. 点击 ...
        3. 输入 ...
        4. 观察到 ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      placeholder: 你期望发生什么？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      placeholder: 实际发生了什么？
    validations:
      required: true

  - type: dropdown
    id: app_scope
    attributes:
      label: 影响范围
      options:
        - ai-chat-nextjs
        - ai-chat-frontend
        - 两者都有
        - 不确定
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 环境信息
      description: 例如 OS / Node.js / 浏览器版本。
      placeholder: Windows 11, Node 20.18.0, Chrome 121
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 相关日志或截图
      description: 请脱敏后粘贴日志，不要包含密钥。
      render: shell
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充信息
      description: 其他你认为有价值的信息。
