name: Feature Request
description: 提出一个可落地的新功能建议
labels: [enhancement]
title: "[Feature]: "
body:
  - type: textarea
    id: background
    attributes:
      label: 问题背景
      description: 你当前遇到的痛点是什么？
      placeholder: 当前缺少什么能力，导致什么影响？
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 期望方案
      description: 你希望增加的能力与行为。
      placeholder: 希望支持 ...，交互方式为 ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你尝试过的替代实现或妥协方案。
      placeholder: 目前只能通过 ... 临时解决
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: 影响范围
      options:
        - ai-chat-nextjs
        - ai-chat-frontend
        - 两者都有
        - 不确定
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      options:
        - 高（阻塞当前工作）
        - 中（明显提升体验）
        - 低（锦上添花）
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充说明
      description: 可附上草图、参考链接、交互说明等。
